---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml

- name: download archive
  ansible.builtin.import_tasks: download.yml

- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: configure.yml

...
